name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.6', '1', 'nightly']
        firebird-version: ['v3']

    steps:
    - uses: actions/checkout@v2

    - name: Setup FirebirdSQL container
      uses: juarezr/firebirdsql-github-action@v1.0.0
      with:
        version: ${{ matrix.firebird-version }}
        isc_password: "masterkey"

    - uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}
    - uses: julia-actions/julia-buildpkg@v1

    - name: Test
      run: |
        julia --project -e 'using Pkg;Pkg.test()'
