name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.5', '1', 'nightly']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Firebird
      run: |
        sudo apt install firebird3.0-server -y
        sudo cp misc/firebird.conf /etc/firebird/3.0
        sudo systemctl restart firebird3.0
        sudo chmod 0664 /etc/firebird/3.0/SYSDBA.password
        grep '=' /etc/firebird/3.0/SYSDBA.password |sed 's/^/export /' >test_user.env

    - uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}
    - uses: julia-actions/julia-buildpkg@v1

    - name: Test
      run: |
        source test_user.env
        julia --project -e 'using Pkg;Pkg.test()'
